f=open("abc.txt","w")
f.write("hello world\n")
f.write("how are you\n")
f.write("i am fine\n")
f.write("i am ok\n")
f=open("abc.txt","r")
s=f.read()
print(s)
f=open("abc.txt","r") 
s1=f.readline()
print(s1)
f=open("abc.txt","a+")
f.write("and you\n")
f.seek(0)
s2=f.read()
print(s2)
